#Step A: Feature Engineering. Process variables like "Time since last refill."

#Step B: XGBoost Implementation. Train the model to identify patterns in discontinuation.

#Step C: SHAP Integration. This is critical. It generates a summary plot showing exactly why a patient is predicted to drop off.

import pandas as pd
import xgboost as xgb
import shap
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, roc_auc_score

def train_adherence_model(data_path='synthetic_patient_data.csv'):
    # 1. Load the data generated by generate_data.py
    df = pd.read_csv(data_path)
    
    # Define features and target
    X = df.drop(['patient_id', 'discontinued'], axis=1)
    y = df['discontinued']
    
    # 2. Split into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    
    # 3. Initialize and train XGBoost Classifier
    print("Training XGBoost model for adherence prediction...")
    model = xgb.XGBClassifier(
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        random_state=42,
        use_label_encoder=False,
        eval_metric='logloss'
    )
    model.fit(X_train, y_train)
    
    # 4. Evaluate Performance
    y_pred = model.predict(X_test)
    auc = roc_auc_score(y_test, model.predict_proba(X_test)[:, 1])
    print("\n--- Model Performance ---")
    print(f"ROC-AUC Score: {auc:.2f}")
    print(classification_report(y_test, y_pred))
    
    # 5. SHAP Integration (Explainable AI)
    print("\nGenerating SHAP explanations...")
    explainer = shap.TreeExplainer(model)
    shap_values = explainer.shap_values(X_test)
    
    # Save the plot for the GitHub README
    plt.figure(figsize=(10, 6))
    shap.summary_plot(shap_values, X_test, show=False)
    plt.title("Feature Importance: Drivers of Therapy Discontinuation", fontsize=14)
    plt.tight_layout()
    plt.savefig('shap_summary.png')
    print("Success! 'shap_summary.png' has been created for your portfolio.")

if __name__ == "__main__":
    train_adherence_model()
